#pragma once

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/spi_master.h"

#define DESKMON_I2C_SDA_GPIO GPIO_NUM_32
#define DESKMON_I2C_SCL_GPIO GPIO_NUM_25
#define DESKMON_I2C_PORT I2C_NUM_0
#define DESKMON_I2C_FREQ_HZ 100000

#define DESKMON_TSL2591_I2C_ADDR 0x29
#define DESKMON_ENS160_I2C_ADDR 0x53
#define DESKMON_AHT20_I2C_ADDR 0x38

#define DESKMON_BUTTON_1_GPIO GPIO_NUM_35
#define DESKMON_BUTTON_2_GPIO GPIO_NUM_39
#define DESKMON_BUTTONS_ENABLED 0

#define DESKMON_DISPLAY_ENABLED 0
#define DESKMON_DISPLAY_SPI_HOST SPI2_HOST
#define DESKMON_DISPLAY_WIDTH 320
#define DESKMON_DISPLAY_HEIGHT 480

/* SPI display pins are not assigned yet. Keep them invalid until the wiring is final. */
#define DESKMON_DISPLAY_MOSI_GPIO GPIO_NUM_NC
#define DESKMON_DISPLAY_SCLK_GPIO GPIO_NUM_NC
#define DESKMON_DISPLAY_CS_GPIO GPIO_NUM_NC
#define DESKMON_DISPLAY_DC_GPIO GPIO_NUM_NC
#define DESKMON_DISPLAY_RST_GPIO GPIO_NUM_NC
#define DESKMON_DISPLAY_BL_GPIO GPIO_NUM_NC
